/* Unverified bootstrap constants for direct 2A2T bring-up. */
#ifndef UWB_2A2T_CONFIG_H
#define UWB_2A2T_CONFIG_H

#define UWB_2A2T_PROFILE_BOOTSTRAP_SAFE         1U
#define UWB_2A2T_PROFILE_CONSERVATIVE_TARGET    2U

#ifndef UWB_2A2T_PROFILE
#define UWB_2A2T_PROFILE UWB_2A2T_PROFILE_BOOTSTRAP_SAFE
#endif

#if UWB_2A2T_PROFILE != UWB_2A2T_PROFILE_BOOTSTRAP_SAFE && \
    UWB_2A2T_PROFILE != UWB_2A2T_PROFILE_CONSERVATIVE_TARGET
#error "Unknown UWB_2A2T_PROFILE"
#endif

/* All values are UUS and are CODE_BASELINE_UNVERIFIED until logic capture. */
#define UWB_2A2T_POLL_TX_TO_RESP_RX_DELAY_UUS   1500U
#define UWB_2A2T_POLL_RX_TO_RESP_TX_DELAY_UUS   1650U
#define UWB_2A2T_RESP_TX_TO_FINAL_RX_DELAY_UUS  1500U
#define UWB_2A2T_RESP_RX_TO_FINAL_TX_DELAY_UUS  1650U
#define UWB_2A2T_FINAL_TX_TO_POST_FINAL_DELAY_UUS 1650U
#define UWB_2A2T_FINAL_RX_TO_POST_FINAL_RX_DELAY_UUS 1500U
#define UWB_2A2T_POST_FINAL_RX_TO_REPORT_DELAY_UUS 2522U
#define UWB_2A2T_RESPONSE_RX_TIMEOUT_UUS        281U
#define UWB_2A2T_FINAL_RX_TIMEOUT_UUS           298U
#define UWB_2A2T_POST_FINAL_RX_TIMEOUT_UUS      279U
#define UWB_2A2T_REPORT_RX_TIMEOUT_UUS          6000U
#define UWB_2A2T_TOKEN_RX_TIMEOUT_UUS           6000U
#define UWB_2A2T_BOOTSTRAP_GUARD_UUS            1000U
#define UWB_2A2T_PREAMBLE_TIMEOUT_PAC           5U
#define UWB_2A2T_SLOT_TIMEOUT_UUS               7000U

#if UWB_2A2T_REPORT_RX_TIMEOUT_UUS > UWB_2A2T_SLOT_TIMEOUT_UUS
#error "Report timeout must fit within a bootstrap slot"
#endif

/* Phase/CIR is intentionally off for the first 2A2T HIL profile. */
#define UWB_2A2T_CIR_PHASE_ENABLE               0U
#define UWB_2A2T_UART_RECORD_SIZE               64U
#define UWB_2A2T_TRACE_RING_CAPACITY            16U

#endif /* UWB_2A2T_CONFIG_H */
