#!/usr/bin/env python3
"""Apply the Phase 6 overlay to one clean, commit-pinned SDK role sandbox."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:  # Supports both direct CLI invocation and pytest imports.
    from ._common import ROOT
except ImportError:  # pragma: no cover - direct CLI invocation
    from _common import ROOT


ROLE_SPECS = {
    "anchor_a1": {"selection": "ds-2a2t-anchor-a1", "node": "A1", "role": "ANCHOR"},
    "anchor_a2": {"selection": "ds-2a2t-anchor-a2", "node": "A2", "role": "ANCHOR"},
    "tag_t1": {"selection": "ds-2a2t-tag-t1", "node": "T1", "role": "TAG_COORDINATOR"},
    "tag_t2": {"selection": "ds-2a2t-tag-t2", "node": "T2", "role": "TAG_FOLLOWER"},
}
OVERLAY_FILES = (
    "ds_twr_2a2t_tag.c",
    "ds_twr_2a2t_anchor.c",
    "uwb_2a2t_config.h",
    "uwb_2a2t_build_identity.h",
    "uwb_2a2t_protocol.h",
    "uwb_2a2t_trace.h",
    "uwb_2a2t_trace.c",
)
BASELINE_FILES = (
    "ds_twr_initiator_final.c",
    "ds_twr_responder_final.c",
)
PROJECT_RELATIVE = Path("API/nRF52840-DK/dw3000_api.emProject")
EXAMPLE_INFO_RELATIVE = Path("API/Src/examples/examples_info/example_info.c")
SELECTION_RELATIVE = Path("API/Src/example_selection.h")


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def canonical_sha256(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def git_text(path: Path, *args: str) -> str:
    completed = subprocess.run(["git", "-C", str(path), *args], check=True, capture_output=True, text=True)
    return completed.stdout.strip()


def require_clean_sdk(sdk_root: Path) -> str:
    if not (sdk_root / ".git").exists():
        raise ValueError(f"SDK sandbox is not a git worktree: {sdk_root}")
    status = git_text(sdk_root, "status", "--porcelain=v1")
    if status:
        raise ValueError("SDK sandbox must be clean before overlay application")
    return git_text(sdk_root, "rev-parse", "HEAD")


def update_project(project_path: Path) -> dict[str, str]:
    before = project_path.read_text(encoding="utf-8")
    text = before
    if "../Src/custom_code;" not in text:
        marker = "../Src/Shared_jang;"
        if marker not in text:
            raise ValueError("cannot locate project include-directory anchor")
        text = text.replace(marker, marker + "../Src/custom_code;", 1)
    folder = '<folder Name="custom_code">'
    start = text.find(folder)
    if start < 0:
        raise ValueError("cannot locate custom_code folder in .emProject")
    end = text.find("</folder>", start)
    if end < 0:
        raise ValueError("cannot locate custom_code folder end in .emProject")
    additions = []
    for name in ("ds_twr_2a2t_tag.c", "ds_twr_2a2t_anchor.c", "uwb_2a2t_trace.c"):
        entry = f'          <file file_name="../Src/custom_code/{name}" />'
        if entry not in text:
            additions.append(entry)
    if additions:
        text = text[:end] + "\n" + "\n".join(additions) + "\n        " + text[end:]
    project_path.write_text(text, encoding="utf-8", newline="\n")
    return {"before_sha256": hashlib.sha256(before.encode("utf-8")).hexdigest(), "after_sha256": sha256_file(project_path)}


def update_example_registration(path: Path) -> dict[str, str]:
    before = path.read_text(encoding="utf-8")
    text = before
    if "#ifdef DS_TWR_2A2T_TAG" not in text:
        marker = "#ifdef DS_TWR_INITIATOR_FINAL"
        if marker not in text:
            raise ValueError("cannot locate example registration anchor")
        registration = """#ifdef DS_TWR_2A2T_TAG
    extern int ds_twr_2a2t_tag(void);

    example_pointer=ds_twr_2a2t_tag;
    test_cnt++;
#endif

#ifdef DS_TWR_2A2T_ANCHOR
    extern int ds_twr_2a2t_anchor(void);

    example_pointer=ds_twr_2a2t_anchor;
    test_cnt++;
#endif

"""
        text = text.replace(marker, registration + marker, 1)
    path.write_text(text, encoding="utf-8", newline="\n")
    return {"before_sha256": hashlib.sha256(before.encode("utf-8")).hexdigest(), "after_sha256": sha256_file(path)}


def write_identity(destination: Path, *, spec: dict[str, str], source_commit: str, overlay_sha256: str, config_sha256: str, timestamp: str) -> str:
    fwid = (
        f"FWID|node={spec['node']}|role={spec['role']}|source_git={source_commit}|"
        f"overlay_sha256={overlay_sha256}|config_sha256={config_sha256}|build_timestamp={timestamp}"
    )
    destination.write_text(
        "/* Generated by tools/prepare_phase6_sdk_sandbox.py. */\n"
        "#ifndef UWB_2A2T_BUILD_IDENTITY_H\n#define UWB_2A2T_BUILD_IDENTITY_H\n"
        f"#define UWB_2A2T_FWID \"{fwid}\"\n"
        "#endif /* UWB_2A2T_BUILD_IDENTITY_H */\n",
        encoding="utf-8",
        newline="\n",
    )
    return fwid


def apply_overlay(sdk_root: Path, role: str) -> dict[str, Any]:
    spec = ROLE_SPECS[role]
    sdk_commit = require_clean_sdk(sdk_root)
    source_commit = git_text(ROOT, "rev-parse", "HEAD")
    source_dir = ROOT / "firmware_overlay" / "API" / "Src" / "custom_code"
    destination_dir = sdk_root / "API" / "Src" / "custom_code"
    project_path = sdk_root / PROJECT_RELATIVE
    registration_path = sdk_root / EXAMPLE_INFO_RELATIVE
    selection_path = sdk_root / SELECTION_RELATIVE
    for path in (destination_dir, project_path, registration_path, selection_path):
        if not path.exists():
            raise FileNotFoundError(f"SDK layout is missing required path: {path}")

    baseline_before = {name: sha256_file(destination_dir / name) for name in BASELINE_FILES}
    source_hashes = {name: sha256_file(source_dir / name) for name in OVERLAY_FILES}
    overlay_sha256 = canonical_sha256(source_hashes)
    config_input = {
        "role": role,
        "node": spec["node"],
        "role_name": spec["role"],
        "project": PROJECT_RELATIVE.as_posix(),
        "build_configuration": "Debug",
        "target_device": "nRF52840_xxAA",
        "sdk_commit": sdk_commit,
        "source_commit": source_commit,
    }
    config_sha256 = canonical_sha256(config_input)
    timestamp = datetime.now(timezone.utc).isoformat()
    for name in OVERLAY_FILES:
        shutil.copy2(source_dir / name, destination_dir / name)
    fwid = write_identity(
        destination_dir / "uwb_2a2t_build_identity.h",
        spec=spec,
        source_commit=source_commit,
        overlay_sha256=overlay_sha256,
        config_sha256=config_sha256,
        timestamp=timestamp,
    )
    project_change = update_project(project_path)
    registration_change = update_example_registration(registration_path)
    selector = ROOT / "tools" / "set_uwb_example.py"
    subprocess.run(
        [sys.executable, str(selector), spec["selection"], "--path", str(selection_path)],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    baseline_after = {name: sha256_file(destination_dir / name) for name in BASELINE_FILES}
    if baseline_before != baseline_after:
        raise RuntimeError("overlay changed a baseline firmware source")
    required_project_sources = [
        f"../Src/custom_code/{name}"
        for name in ("ds_twr_2a2t_tag.c", "ds_twr_2a2t_anchor.c", "uwb_2a2t_trace.c")
    ]
    project_text = project_path.read_text(encoding="utf-8")
    if "../Src/custom_code;" not in project_text or any(item not in project_text for item in required_project_sources):
        raise RuntimeError("project does not explicitly include Phase 6 custom sources")
    if f"#define UWB_2A2T_FWID \"{fwid}\"" not in (destination_dir / "uwb_2a2t_build_identity.h").read_text(encoding="utf-8"):
        raise RuntimeError("generated FWID identity header is inconsistent")
    return {
        "source_type": "CODE_INSPECTION_AND_BUILD",
        "hardware_verified": False,
        "flash_executed": False,
        "role": role,
        "node_id": spec["node"],
        "role_name": spec["role"],
        "selection": spec["selection"],
        "sdk_root": str(sdk_root),
        "sdk_commit": sdk_commit,
        "source_commit": source_commit,
        "overlay_sha256": overlay_sha256,
        "overlay_files": source_hashes,
        "config_sha256": config_sha256,
        "build_timestamp": timestamp,
        "fwid": fwid,
        "baseline_before": baseline_before,
        "baseline_after": baseline_after,
        "project_change": project_change,
        "registration_change": registration_change,
        "post_overlay_git_status": git_text(sdk_root, "status", "--porcelain=v1").splitlines(),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk-root", type=Path, required=True)
    parser.add_argument("--role", choices=sorted(ROLE_SPECS), required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.manifest.exists():
        raise SystemExit(f"refusing to overwrite overlay manifest: {args.manifest}")
    try:
        result = apply_overlay(args.sdk_root.resolve(), args.role)
        args.manifest.parent.mkdir(parents=True, exist_ok=True)
        args.manifest.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    except (FileNotFoundError, RuntimeError, ValueError, subprocess.CalledProcessError) as exc:
        raise SystemExit(f"[FAIL] {type(exc).__name__}: {exc}") from exc
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
